// front-end-2/src/pages/ProjectsPage/features/ProjectPreview/ProjectPreview.tsx
import { FunctionComponent } from 'react';
import { NavLink } from 'react-router-dom';
import { ProjectPreview } from '../../../../services';
import './ProjectPreview.scss';

function createRouterLink(project: ProjectPreview): string {
  return '/project/' + project.code;
}

const ProjectPreviewComponent: FunctionComponent<{project: ProjectPreview}> = (props) => {
  return (
  <div className="container-project-preview">
    <img className={props.project.releaseDate ? 'poster' : 'poster grayscale-filter'}
         src={ props.project.posterUrl || '/assets/images/placeholder-wide.png' }
         alt={ props.project.posterDescription }/>
    
    <div className="content">
      <NavLink to={createRouterLink(props.project)} className="headline">
        [{ props.project.category?.displayName }] { props.project.displayName }
      </NavLink>

      <div className="description" dangerouslySetInnerHTML={{__html: props.project.description}} />
    </div>
  </div>
  );
}

export default ProjectPreviewComponent;

// front-end/BusinessSite/src/app/component/project-preview/project-preview.component.ts
import { Component, Input } from '@angular/core';

import { Project } from 'src/app/model/Project';

@Component({
  selector: 'app-project-preview',
  templateUrl: './project-preview.component.html',
  styleUrls: ['./project-preview.component.scss']
})

export class ProjectPreviewComponent {

  @Input()
  public project: Project;

  public createRouterLink(): string {
    return '/project/' + this.project.code;
  }
}

<div class="container" fxLayout="column" fxLayoutAlign="end stretch">
  <img 
  [className]="project.releaseDate ? 'image' : 'image image-gray'"
       src="{{(project.posterUrl || '\\assets\\images\\placeholder-wide.png')}}"
       alt="{{project.posterDescription}}" />

  <div class="content">
    <a class="headline" [routerLink]="createRouterLink()">[{{project.category?.displayName}}] {{ project.displayName }}</a>
    <div class="description" [innerHtml]="project.description"></div>   
  </div>
</div>
