// front-end/src/app/projects/button-category/button-category.component.ts
import { Component, Input } from '@angular/core';
import { Category } from '../../shared/models/category.model';

@Component({
  selector: 'app-button-category',
  templateUrl: './button-category.component.html',
  styleUrls: ['./button-category.component.scss'],
})
export class ButtonCategoryComponent {
  @Input()
  public route: string;

  @Input()
  public category: Category;
}

<a class="{{ rla.isActive ? 'flat-button active' : 'flat-button' }}" 
   #rla="routerLinkActive"
   routerLinkActive
   [routerLink]="route"
   [routerLinkActiveOptions]="{ exact: false }">

   <div fxLayout="row" class="content">
    <div fxFlex class="display-name">{{category.displayName}}</div>
    <div class="counter-container">
      <div class="conter-content">
        {{category.totalProjects}}
      </div>
    </div>
  </div> 

</a>

// front-end-2/src/pages/ProjectsPage/features/ButtonCategory/ButtonCategoryComponent.tsx
import { FunctionComponent } from 'react';
import { NavLink } from 'react-router-dom';
import { Category } from '../../../../services/models/_index';
import './ButtonCategoryComponent.scss';

const ButtonCategoryComponent: FunctionComponent<{category: Category}> = (props) => {
  return (
    <NavLink to='/projects' className="flat-button">
      <div className="content">
        <div className="display-name">{ props.category.displayName }</div>
        <div className="counter-container">
          <div className="conter-content">
            { props.category.totalProjects }
          </div>
        </div>
      </div>
    </NavLink>
  );
}

export default ButtonCategoryComponent;
