// front-end-2/src/pages/IntroductionPage/features/buttonContact/buttonContact.tsx
import './buttonContact.scss';

function ButtonContact(key: any, url: string, displayName: string) {
  return (
    <a className="button-contact"
       rel="noreferrer noopener"
       target="_blank"
       key = { key } 
       href = { url }>
      <span> { displayName } </span>
    </a>
)};

export default ButtonContact;

// front-end/BusinessSite/src/app/component/button-contact/button-contact.component.ts
import { Component, Input } from '@angular/core';
import { ExternalUrl } from 'src/app/model/ExternalUrl';

@Component({
  selector: 'app-button-contact',
  templateUrl: './button-contact.component.html',
  styleUrls: ['./button-contact.component.scss']
})

export class ButtonContactComponent
{
  @Input()
  public externalUrl: ExternalUrl;
}

<a class="flat-link" href="{{externalUrl.url}}" rel="noreferrer noopener" target="_blank">
  <span> {{externalUrl.displayName}}</span>
</a>
